Added column selector
blackbaud/skyux-list-builder-view-grids pull request #3
Opened 2018-10-26 18:56 UTC by Blackbaud-AlexKingman

2018-10-26 19:24 UTC, Blackbaud-SteveBrush requested changes

2018-10-26 19:24 UTC, Blackbaud-SteveBrush commented on src/assets/locales/resources_en_US.json
> +  "grid_column_picker_cancel": {
Should be prefixed with `skyux_`. Also, did you implement the new `skyLibResources` pipe, and `SkyLibResourcesService`?

2018-10-29 13:39 UTC, Blackbaud-AlexKingman commented on src/assets/locales/resources_en_US.json
> +  "grid_column_picker_cancel": {
this should all be cleared up now.

2018-10-29 14:08 UTC, Blackbaud-SteveBrush approved these changes

2018-10-29 14:08 UTC, merged